// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4oW0ymXLp4sIhJ0RhNYXSpFlPfyvNOqA',
    appId: '1:965768700070:web:8b76f7f30b2a340bf35467',
    messagingSenderId: '965768700070',
    projectId: 'werewolf-game-d6482',
    authDomain: 'werewolf-game-d6482.firebaseapp.com',
    storageBucket: 'werewolf-game-d6482.firebasestorage.app',
    measurementId: 'G-1FBNM7DQJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg3OPCq9k1eCF5hSFaHZ6HTNB_TikPH7o',
    appId: '1:965768700070:android:f00793f54fa367f4f35467',
    messagingSenderId: '965768700070',
    projectId: 'werewolf-game-d6482',
    storageBucket: 'werewolf-game-d6482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWrGQ-ueJKCHelUivFp_GlzcUIwNdhVyI',
    appId: '1:965768700070:ios:38cc6aa991e07118f35467',
    messagingSenderId: '965768700070',
    projectId: 'werewolf-game-d6482',
    storageBucket: 'werewolf-game-d6482.firebasestorage.app',
    iosBundleId: 'com.example.werewolfGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWrGQ-ueJKCHelUivFp_GlzcUIwNdhVyI',
    appId: '1:965768700070:ios:38cc6aa991e07118f35467',
    messagingSenderId: '965768700070',
    projectId: 'werewolf-game-d6482',
    storageBucket: 'werewolf-game-d6482.firebasestorage.app',
    iosBundleId: 'com.example.werewolfGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4oW0ymXLp4sIhJ0RhNYXSpFlPfyvNOqA',
    appId: '1:965768700070:web:eb7ff1d47d6bc0f1f35467',
    messagingSenderId: '965768700070',
    projectId: 'werewolf-game-d6482',
    authDomain: 'werewolf-game-d6482.firebaseapp.com',
    storageBucket: 'werewolf-game-d6482.firebasestorage.app',
    measurementId: 'G-TEZ34WD0W8',
  );
}
